#pragma once

#include "../Common/Common.h"

#define DEVICE_GPIO_1  D0
#define DEVICE_GPIO_2  D1
#define DEVICE_GPIO_3  D2
#define DEVICE_GPIO_4  D3
#define DEVICE_GPIO_5  D4
#define DEVICE_GPIO_6  D5
#define DEVICE_GPIO_7  D6
#define DEVICE_GPIO_8  D7
#define DEVICE_GPIO_9  D8
#define DEVICE_GPIO_10 D9
#define DEVICE_GPIO_11 D10

#define DEVICE_PIN_STATUS_LED_R DEVICE_GPIO_1
#define DEVICE_PIN_STATUS_LED_G DEVICE_GPIO_2
#define DEVICE_PIN_STATUS_LED_B DEVICE_GPIO_3

#define DEVICE_PIN_OUTPUT_FASTLED DEVICE_GPIO_4
#define DEVICE_PIN_LCD_SCL DEVICE_GPIO_5
#define DEVICE_PIN_LCD_SDA DEVICE_GPIO_6
