#pragma once

#include "../Common/Common.h"

#define DEVICE_GPIO_1  23
#define DEVICE_GPIO_2  22
#define DEVICE_GPIO_3  21
#define DEVICE_GPIO_4  19
#define DEVICE_GPIO_5  18
#define DEVICE_GPIO_6  17
#define DEVICE_GPIO_7  33
#define DEVICE_GPIO_8  32
#define DEVICE_GPIO_9  27
#define DEVICE_GPIO_10 26
#define DEVICE_GPIO_11 25
#define DEVICE_GPIO_12 4
#define DEVICE_GPIO_13 34

#define DEVICE_PIN_STATUS_LED_R DEVICE_GPIO_1
#define DEVICE_PIN_STATUS_LED_G DEVICE_GPIO_2
#define DEVICE_PIN_STATUS_LED_B DEVICE_GPIO_3

#define DEVICE_PIN_OUTPUT_FASTLED_0 DEVICE_GPIO_4
#define DEVICE_PIN_OUTPUT_FASTLED_1 DEVICE_GPIO_8

#define DEVICE_PIN_LCD_SCL DEVICE_GPIO_5
#define DEVICE_PIN_LCD_SDA DEVICE_GPIO_6

#define DEVICE_PIN_BUTTON_LEFT DEVICE_GPIO_11
#define DEVICE_PIN_BUTTON_ENTER DEVICE_GPIO_10
#define DEVICE_PIN_BUTTON_RIGHT DEVICE_GPIO_9

#define DEVICE_PIN_ENABLE_POWER  DEVICE_GPIO_12
#define DEVICE_PIN_ANALOG_BUTTON DEVICE_GPIO_13
